* Newspeak mode

Major mode (/Emacs/) for the [[https://newspeaklanguage.org/][Newspeak]] programming language.

/Caveat emptor/: This is a work in progress.

** Installation

*** MELPA

Newspeak mode will be available via the MELPA repository. Meanwhile, please refer to the section below.

*** Manually

- Clone this repository.
- Add the following to your initialization file (e.g. ~init.el~):
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "~/path/to/newspeak-mode"))
(require 'newspeak-mode)
#+end_src

** Features

*** Syntax highlighting

Fully configurable under the customization group ~newspeak-mode-faces~.

The following are different ways to customize syntax highlighting of Newspeak mode, and all are equally valid.

- ~M-x customize~ and type ~newspeak~ in the search bar.
- ~M-x customize-group~ and select ~newspeak~
- ~M-x customize-face~, type ~newspeak~ and press ~TAB~ for completion.
   
The font lock system is mapped onto Newspeak constructs in the following way.

| Font lock          | Newspeak construct       |
|--------------------+--------------------------|
|                    |                          |
| Builtin Face       | Access modifiers         |
| Comment Face       | Comments                 |
| Constant Face      | Reserved keywords        |
| Function Name Face | Keyword and setter sends |
| Keyword Face       | Block arguments          |
| String Face        | Strings                  |
| Type Face          | Types                    |
| Variable Name      | Slot assignments         |
| Warning Face       | Language shebang         |

Modify the faces at will.

**** Matching parentheses

Because this is Emacs, matching parentheses is best left to the myriad of modes available to achieve just that. Perhaps ~M-x show-paren-mode~ is here of interest. [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] works nicely, too.

#+begin_src emacs-lisp
(add-hook 'newspeak-mode-hook 'rainbow-delimiters-mode)
#+end_src
*** Indentation

The indentation logic uses a backward parsing strategy aided by a bespoke bi-directional scanner that understands Newspeak syntactic constructs.

The file ~sample.ns~ contains the commentary about how a Newspeak source file should be indented. It is canonical since those words come straight from the author of the language, [[https://github.com/gbracha][Gilad Bracha]].

Caveat: the indentation engine does not yet fulfill its contract.

** Road map

- [✓] Syntax highlighting
- [✓] Automatic indentation.
- [✓] Syntax-aware navigation.
- [ ] Code templates.
- [ ] REPL interaction
- [✓] Support for prettify-symbols-mode.
- [ ] Keyboard shortcuts

